### ISSUE TITLE
Heroku build seems to be failing.

### ISSUE THREAD

**Issue by ghost** [kenny-hibino/stories#57]
```
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.3.3
-----> Installing dependencies using bundler 1.15.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from https://rubygems.org/.......
       Fetching version metadata from https://rubygems.org/..
       Fetching dependency metadata from https://rubygems.org/.
       Fetching rake 11.1.2
       Fetching i18n 0.7.0
       Using json 1.8.3
       Fetching minitest 5.8.4
       Installing i18n 0.7.0
       Installing minitest 5.8.4
       Installing rake 11.1.2
       Fetching thread_safe 0.3.5
       Installing thread_safe 0.3.5
       Fetching builder 3.2.2
       Installing builder 3.2.2
       Fetching erubis 2.7.0
       Fetching mini_portile2 2.0.0
       Fetching rack 1.6.4
       Installing mini_portile2 2.0.0
       Installing erubis 2.7.0
       Fetching mime-types-data 3.2016.0221
       Installing rack 1.6.4
       Installing mime-types-data 3.2016.0221
       Fetching arel 6.0.3
       Installing arel 6.0.3
       Fetching execjs 2.6.0
       Installing execjs 2.6.0
       Fetching babel-source 5.8.35
       Fetching bcrypt 3.1.11
       Installing bcrypt 3.1.11 with native extensions
       Installing babel-source 5.8.35
       Fetching bonsai-elasticsearch-rails 0.0.4
       Fetching sass 3.4.21
       Installing bonsai-elasticsearch-rails 0.0.4
       Using bundler 1.15.2
       Fetching coffee-script-source 1.10.0
       Installing sass 3.4.21
       Installing coffee-script-source 1.10.0
       Fetching thor 0.19.1
       Installing thor 0.19.1
       Fetching concurrent-ruby 1.0.1
       Installing concurrent-ruby 1.0.1
       Fetching connection_pool 2.2.0
       Installing connection_pool 2.2.0
       Fetching dalli 2.7.6
       Fetching orm_adapter 0.5.0
       Installing orm_adapter 0.5.0
       Installing dalli 2.7.6
       Fetching multi_json 1.11.2
       Fetching multipart-post 2.0.0
       Installing multipart-post 2.0.0
       Installing multi_json 1.11.2
       Fetching hashie 3.4.3
       Fetching elasticsearch-rails 0.1.8
       Installing hashie 3.4.3
       Fetching excon 0.48.0
       Installing excon 0.48.0
       Installing elasticsearch-rails 0.1.8
       Fetching formatador 0.2.5
       Installing formatador 0.2.5
       Fetching inflecto 0.0.2
       Installing inflecto 0.0.2
       Fetching ipaddress 0.8.3
       Installing ipaddress 0.8.3
       Fetching jwt 1.5.1
       Fetching subexec 0.2.3
       Installing jwt 1.5.1
       Installing subexec 0.2.3
       Fetching multi_xml 0.5.5
       Fetching net-ssh 3.1.1
       Installing multi_xml 0.5.5
       Fetching oauth 0.5.1
       Installing net-ssh 3.1.1
       Installing oauth 0.5.1
       Fetching pg 0.18.4
       Fetching puma 2.16.0
       Installing pg 0.18.4 with native extensions
       Installing puma 2.16.0 with native extensions
       Fetching rails_serve_static_assets 0.0.5
       Installing rails_serve_static_assets 0.0.5
       Fetching rails_stdout_logging 0.0.5
       Installing rails_stdout_logging 0.0.5
       Fetching tilt 2.0.2
       Installing tilt 2.0.2
       Fetching redis 3.2.2
       Installing redis 3.2.2
       Fetching temple 0.7.6
       Installing temple 0.7.6
       Fetching will_paginate 3.1.0
       Installing will_paginate 3.1.0
       Fetching rdoc 4.2.2
       Installing rdoc 4.2.2
       Fetching tzinfo 1.2.2
       Installing tzinfo 1.2.2
       Fetching nokogiri 1.6.7.2
       Installing nokogiri 1.6.7.2 with native extensions
       Fetching mime-types 3.0
       Installing mime-types 3.0
       Fetching autoprefixer-rails 6.3.4
       Installing autoprefixer-rails 6.3.4
       Fetching uglifier 3.0.0
       Installing uglifier 3.0.0
       Fetching rack-test 0.6.3
       Installing rack-test 0.6.3
       Fetching warden 1.2.6
       Installing warden 1.2.6
       Fetching rack-protection 1.5.3
       Installing rack-protection 1.5.3
       Fetching babel-transpiler 0.7.0
       Installing babel-transpiler 0.7.0
       Fetching coffee-script 2.4.1
       Installing coffee-script 2.4.1
       Fetching font-awesome-sass 4.5.0
       Installing font-awesome-sass 4.5.0
       Fetching sprockets 3.6.0
       Installing sprockets 3.6.0
       Fetching faraday 0.9.2
       Installing faraday 0.9.2
       Fetching elasticsearch-api 1.0.15
       Installing elasticsearch-api 1.0.15
       Fetching omniauth 1.3.1
       Installing omniauth 1.3.1
       Fetching fog-core 1.36.0
       Installing fog-core 1.36.0
       Fetching mini_magick 3.8.0
       Installing mini_magick 3.8.0
       Fetching rails_12factor 0.0.2
       Installing rails_12factor 0.0.2
       Fetching sidekiq 4.1.1
       Installing sidekiq 4.1.1
       Fetching slim 3.0.6
       Installing slim 3.0.6
       Fetching sdoc 0.4.1
       Installing sdoc 0.4.1
       Fetching activesupport 4.2.6
       Installing activesupport 4.2.6
       Fetching mail 2.6.4
       Fetching bootstrap-sass 3.3.6
       Installing bootstrap-sass 3.3.6
       Installing mail 2.6.4
       Fetching sinatra 1.4.7
       Fetching elasticsearch-transport 1.0.15
       Installing sinatra 1.4.7
       Installing elasticsearch-transport 1.0.15
       Fetching oauth2 1.1.0
       Installing oauth2 1.1.0
       Fetching omniauth-oauth 1.1.0
       Fetching fog-json 1.0.2
       Installing fog-json 1.0.2
       Installing omniauth-oauth 1.1.0
       Fetching rails-deprecated_sanitizer 1.0.3
       Fetching globalid 0.3.6
       Installing globalid 0.3.6
       Installing rails-deprecated_sanitizer 1.0.3
       Fetching activemodel 4.2.6
       Fetching jbuilder 2.4.1
       Installing activemodel 4.2.6
       Installing jbuilder 2.4.1
       Fetching elasticsearch 1.0.15
       Fetching omniauth-oauth2 1.4.0
       Installing elasticsearch 1.0.15
       Installing omniauth-oauth2 1.4.0
       Fetching fog-brightbox 0.10.1
       Fetching fog-softlayer 1.1.0
       Installing fog-brightbox 0.10.1
       Installing fog-softlayer 1.1.0
       Fetching omniauth-twitter 1.2.1
       Fetching activejob 4.2.6
       Installing omniauth-twitter 1.2.1
       Installing activejob 4.2.6
       Fetching activerecord 4.2.6
       Fetching carrierwave 0.10.0
       Installing activerecord 4.2.6
       Installing carrierwave 0.10.0
       Fetching elasticsearch-model 0.1.8
       Installing elasticsearch-model 0.1.8
       Fetching omniauth-facebook 3.0.0
       Fetching omniauth-google-oauth2 0.3.1
       Installing omniauth-facebook 3.0.0
       Installing omniauth-google-oauth2 0.3.1
       Fetching friendly_id 5.1.0
       Installing friendly_id 5.1.0
       Fetching rails-dom-testing 1.0.7
       Fetching loofah 2.0.3
       Fetching fog 1.23.0
       Installing rails-dom-testing 1.0.7
       Installing loofah 2.0.3
       Fetching rails-html-sanitizer 1.0.3
       Installing rails-html-sanitizer 1.0.3
       Fetching actionview 4.2.6
       Installing actionview 4.2.6
       Installing fog 1.23.0
       Fetching actionpack 4.2.6
       Installing actionpack 4.2.6
       Fetching actionmailer 4.2.6
       Fetching railties 4.2.6
       Installing actionmailer 4.2.6
       Installing railties 4.2.6
       Fetching sprockets-rails 3.0.4
       Installing sprockets-rails 3.0.4
       Fetching coffee-rails 4.1.1
       Fetching responders 2.1.2
       Installing responders 2.1.2
       Installing coffee-rails 4.1.1
       Fetching jquery-rails 4.1.1
       Fetching jquery-ui-rails 5.0.5
       Installing jquery-ui-rails 5.0.5
       Installing jquery-rails 4.1.1
       Fetching rails 4.2.6
       Fetching react-rails 1.10.0
       Installing rails 4.2.6
       Installing react-rails 1.10.0
       Fetching sass-rails 5.0.4
       Installing sass-rails 5.0.4
       Fetching turbolinks 2.5.3
       Installing turbolinks 2.5.3
       Fetching devise 3.5.6
       Installing devise 3.5.6
       Bundle complete! 54 Gemfile dependencies, 108 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Post-install message from rdoc:
       Depending on your version of ruby, you may need to install ruby rdoc/ri data:
       <= 1.8.6 : unsupported
       = 1.8.7 : gem install rdoc-data; rdoc-data --install
       = 1.9.1 : gem install rdoc-data; rdoc-data --install
       >= 1.9.2 : nothing to do! Yay!
       The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.2.
       To update, run `gem install bundler --pre`
       Bundle completed (27.19s)
       Cleaning up the bundler cache.
       The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.2.
       To update, run `gem install bundler --pre`
-----> Installing node-v6.11.1-linux-x64
-----> Detecting rake tasks
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/fog-1.23.0/lib/fog/rackspace/mock_data.rb:42: warning: key "name" is duplicated and overwritten on line 80
       Starting up a new ElasticSearch client with
       rake aborted!
       ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/fog-core-1.36.0/lib/fog/core/service.rb:244:in `validate_options'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/fog-core-1.36.0/lib/fog/core/service.rb:268:in `handle_settings'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/fog-core-1.36.0/lib/fog/core/service.rb:98:in `new'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/fog-core-1.36.0/lib/fog/core/services_mixin.rb:16:in `new'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/fog-core-1.36.0/lib/fog/storage.rb:27:in `new'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:83:in `eager_load_fog'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:96:in `fog_credentials='
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/config/initializers/carrierwave.rb:5:in `block in <top (required)>'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:118:in `configure'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/carrierwave-0.10.0/lib/carrierwave.rb:14:in `configure'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/config/initializers/carrierwave.rb:4:in `<top (required)>'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/config/environment.rb:5:in `<top (required)>'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
       /tmp/build_2d4aa2b1fa94de850e899f1c74e4063a/gkua-stories-6cf9294/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by sauravtom** [comment]
You'll need to setup AWS S3 bucket credentials in heroku config as shown here https://stackoverflow.com/a/35028081
